export enum ApiErrorMessage {
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    ACCOUNT_WITH_EMAIL_EXISTS = "ACCOUNT_WITH_EMAIL_EXISTS",
    INVALID_AUTH_TOKEN = "INVALID_AUTH_TOKEN",
    INVALID_EMAIL_OR_PASSWORD = "INVALID_EMAIL_OR_PASSWORD",
}
